"""Add VIP and Trending badges to astrologer profile

Revision ID: 493c58105162
Revises: 2f14b689bed0
Create Date: 2026-07-28 16:27:21.672708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '493c58105162'
down_revision: Union[str, Sequence[str], None] = '2f14b689bed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('astrologer_profiles', sa.Column('is_vip', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('astrologer_profiles', sa.Column('is_trending', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astrologer_profiles', 'is_trending')
    op.drop_column('astrologer_profiles', 'is_vip')
    # ### end Alembic commands ###
