"""initial_migration

Revision ID: 6634fab95ab9
Revises: 
Create Date: 2026-01-13 21:07:55.925558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6634fab95ab9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('verification_type', sa.Enum('FORGOT_PASSWORD', 'EMAIL_VERIFICATION', name='verificationtokentype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=False)
    op.drop_constraint(op.f('astrologer_profiles_user_id_fkey'), 'astrologer_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'astrologer_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_chat_messages_consultation_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_constraint(op.f('chat_messages_consultation_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_sender_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'consultations', ['consultation_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'])
    op.alter_column('consultations', 'consultation_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CHAT', 'VOICE', 'VIDEO', name='consultationtype'),
               existing_nullable=False)
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('REQUESTED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'ACCEPTED', 'ACTIVE', 'PAUSED', 'AUTO_ENDED', 'REJECTED', 'MISSED', name='consultationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'REQUESTED'::character varying"))
    op.drop_index(op.f('idx_consultations_astrologer_id'), table_name='consultations')
    op.drop_index(op.f('idx_consultations_seeker_id'), table_name='consultations')
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.drop_constraint(op.f('consultations_seeker_id_fkey'), 'consultations', type_='foreignkey')
    op.drop_constraint(op.f('consultations_astrologer_id_fkey'), 'consultations', type_='foreignkey')
    op.create_foreign_key(None, 'consultations', 'users', ['astrologer_id'], ['id'])
    op.create_foreign_key(None, 'consultations', 'users', ['seeker_id'], ['id'])
    op.drop_index(op.f('idx_reviews_astrologer_id'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_seeker_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_constraint(op.f('reviews_astrologer_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_consultation_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_seeker_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'consultations', ['consultation_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['seeker_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['astrologer_id'], ['id'])
    op.alter_column('seeker_profiles', 'gender',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'),
               existing_nullable=True)
    op.drop_constraint(op.f('seeker_profiles_user_id_fkey'), 'seeker_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'seeker_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_wallets_user_id_fkey'), 'user_wallets', type_='foreignkey')
    op.create_foreign_key(None, 'user_wallets', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'SEEKER', 'ASTROLOGER', name='userrole'),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_phone_number'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DEPOSIT', 'WITHDRAWAL', 'CHAT_DEDUCTION', 'CHAT_REFUND', name='transactiontype'),
               existing_nullable=False)
    op.drop_index(op.f('idx_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.drop_constraint(op.f('wallet_transactions_user_id_fkey'), 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'wallet_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_transactions_user_id_fkey'), 'wallet_transactions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.create_index(op.f('idx_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=sa.Enum('DEPOSIT', 'WITHDRAWAL', 'CHAT_DEDUCTION', 'CHAT_REFUND', name='transactiontype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'SEEKER', 'ASTROLOGER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'user_wallets', type_='foreignkey')
    op.create_foreign_key(op.f('user_wallets_user_id_fkey'), 'user_wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'seeker_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('seeker_profiles_user_id_fkey'), 'seeker_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('seeker_profiles', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_seeker_id_fkey'), 'reviews', 'users', ['seeker_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_consultation_id_fkey'), 'reviews', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_astrologer_id_fkey'), 'reviews', 'users', ['astrologer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.create_index(op.f('idx_reviews_seeker_id'), 'reviews', ['seeker_id'], unique=False)
    op.create_index(op.f('idx_reviews_astrologer_id'), 'reviews', ['astrologer_id'], unique=False)
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.create_foreign_key(op.f('consultations_astrologer_id_fkey'), 'consultations', 'users', ['astrologer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('consultations_seeker_id_fkey'), 'consultations', 'users', ['seeker_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.create_index(op.f('idx_consultations_seeker_id'), 'consultations', ['seeker_id'], unique=False)
    op.create_index(op.f('idx_consultations_astrologer_id'), 'consultations', ['astrologer_id'], unique=False)
    op.alter_column('consultations', 'status',
               existing_type=sa.Enum('REQUESTED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'ACCEPTED', 'ACTIVE', 'PAUSED', 'AUTO_ENDED', 'REJECTED', 'MISSED', name='consultationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'REQUESTED'::character varying"))
    op.alter_column('consultations', 'consultation_type',
               existing_type=sa.Enum('CHAT', 'VOICE', 'VIDEO', name='consultationtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_sender_id_fkey'), 'chat_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_messages_consultation_id_fkey'), 'chat_messages', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_consultation_id'), 'chat_messages', ['consultation_id'], unique=False)
    op.drop_constraint(None, 'astrologer_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('astrologer_profiles_user_id_fkey'), 'astrologer_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
