services:
  api:
    build: ./api
    container_name: astro_api_staging
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres.tpjjtdtuhdsktudkysmz:Gagbx3lcYMqRbUqQ@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require"
      REDIS_URL: redis://redis:6379/0
    ports:
      - "9000:8000"
    volumes:
      - ./api/uploads:/app/uploads


  web:
    build: 
      context: ./web
      args:
        VITE_API_URL: https://api.aadikarta.org
    container_name: astro_web_staging
    ports:
      - "4002:80"

  admin:
    build:
      context: ./admin
      args:
        VITE_API_URL: https://api.aadikarta.org
    container_name: astro_admin_staging
    ports:
      - "4001:80"

  redis:
    image: "redis:alpine"
    container_name: astro_redis_staging
    ports:
      - "6380:6379"

  mirotalk:
    image: mirotalk/sfu:latest
    container_name: astro_mirotalk_staging
    ports:
      - "4010:3010"
    environment:
      - PORT=3010
      - API_KEY_SECRET=mirotalk_api_secret 
      - JWT_SECRET=mirotalk_secret_key_change_me 



